# This file configures the overall theme of the Chatbot; Changing values here will immediately reflect in the Streamlit cloud hosted version

[theme]
base="light"
primaryColor="#5591f5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#DEFCF9"
textColor="#0a1464"
font="sans serif"
